shared: &shared
  adapter: mysql2
  encoding: utf8
  reconnect: true
  pool: 5
  username: root
  password: password

development:
  <<: *shared
  database: game_sujoy_gupta_development

production:
  <<: *shared
  database: game

sandbox:
  <<: *shared
  database: game_sandbox

test:
  <<: *shared
  database: game_sujoy_gupta_test
