source 'https://rubygems.org'

gem 'globals', '~> 0.2.0'
gem 'guid'
gem 'json', '~> 1.7.7'
gem 'mysql2', '~> 0.3.11'
gem 'rails', '3.2.13'
gem 'sqlite3'

group :development do
  gem 'capistrano', '~> 3.1.0', require: false
  gem 'capistrano-rails', '~> 1.1', require: false
  gem 'capistrano-bundler', '~> 1.1', require: false
  gem 'factory_girl_rails', '~> 4.0'
  gem 'rspec-rails', '~> 2.12.2'
  gem 'webrat', '~> 0.7.3'
end

group :production do
  gem 'therubyracer'
end

